---
services:

  onms-hzn-core:
    depends_on:
      kafka-broker:
        condition: service_started
    volumes:
      - ./container-fs/overlay-etc:/opt/opennms-etc-overlay
    ports:
      - "8980:8980/tcp"
