---
services:
  
  kafka:
    ports:
      - "9092:9092/tcp"

  kafka-ui:
    ports:
      - "8080:8080/tcp"

  core:
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./container-fs/core-etc-overlay:/opt/opennms-etc-overlay
    ports:
      - "8980:8980/tcp"
  
  minion:
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./container-fs/minion-etc-overlay:/opt/minion-etc-overlay
    ports:
      - "162:1162/udp"
      - "514:1514/udp"
