---
services:

  kafka-broker:
    hostname: ip4.en7.blinky.labmonkeys.tech
    environment:
      TZ: UTC
      LOG_DIR: "/tmp/logs"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://ip4.en7.blinky.labmonkeys.tech:9092,PLAINTEXT_HOST://localhost:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ip4.en7.blinky.labmonkeys.tech:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3 # The number of partitions > the number of Minions per Location, default is 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 20000
      KAFKA_LOG_SEGMENT_BYTES: 107374182
      KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: 1000
    ports:
      - "9092:9092/tcp"

  kafka-ui:
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ip4.en7.blinky.labmonkeys.tech:9092
    ports:
      - "8080:8080/tcp"
