---
services:

  mimir:
    ports:
      - "9090:9090/tcp"

  core:
    depends_on:
      elasticsearch:
        condition: service_healthy
      mimir:
        condition: service_started
      kafka-broker:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      JAEGER_SERVICE_NAME: core-kafka-flows-bmp
    volumes:
      - ./container-fs/core-etc-overlay:/opt/opennms-etc-overlay
      - ./container-fs/core-overlay:/opt/opennms-overlay
    ports:
      - "8101:8101/tcp"
      - "8980:8980/tcp"
  
  minion:
    depends_on:
      kafka-broker:
        condition: service_started
    volumes:
      - ./container-fs/minion-etc-overlay:/opt/minion-etc-overlay
    environment:
      JAEGER_SERVICE_NAME: minion-kafka-flows-bmp
    ports:
      - "8201:8201/tcp"
      - "4729:4729/udp"
      - "11019:11019/tcp"
      - "162:1162/udp"
      - "514:1514/udp"

  sentinel:
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kafka-broker:
        condition: service_started
    volumes:
      - ./container-fs/sentinel-etc-overlay:/opt/sentinel-etc-overlay
    ports:
      - "8301:8301/tcp"

  pgadmin:
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "80:80/tcp"

  kafka-ui:
    ports:
      - "8080:8080/tcp"
