---
services:

  mimir:
    ports:
      - "9090:9090/tcp"

  onms-hzn-core:
    depends_on:
      mimir:
        condition: service_started
      kafka-broker:
        condition: service_started
    volumes:
      - ./container-fs/core-etc-overlay:/opt/opennms-etc-overlay
      - ./container-fs/core-overlay:/opt/opennms-overlay
    ports:
      - "8101:8101/tcp"
      - "8980:8980/tcp"
  
  onms-hzn-minion:
    depends_on:
      kafka-broker:
        condition: service_started
    volumes:
      - ./container-fs/minion-etc-overlay:/opt/minion-etc-overlay
    ports:
      - "8201:8201/tcp"

  grafana:
    ports:
      - "3000:3000/tcp"

