---
services:

  kafka-broker:
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.3
        ipv6_address: fd23:9695:aa65:fff0::3
        
  elasticsearch:
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.4
        ipv6_address: fd23:9695:aa65:fff0::4
    volumes:
      - ./container-fs/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"

  database:
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.10
        ipv6_address: fd23:9695:aa65:fff0::10

  core:
    depends_on:
      kafka-broker:
        condition: service_started
    volumes:
      - ./container-fs/core-etc-overlay:/opt/opennms-etc-overlay
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.11
        ipv6_address: fd23:9695:aa65:fff0::11
    ports:
      - "8980:8980/tcp"
  
  grafana:
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.13
        ipv6_address: fd23:9695:aa65:fff0::13
    environment:
      GF_INSTALL_PLUGINS: opennms-opennms-app,grafana-piechart-panel,neocat-cal-heatmap-panel,briangann-datatable-panel
    volumes:
       - ./container-fs/grafana:/etc/grafana/provisioning/
    ports:
      - "3000:3000/tcp"
  
  minion:
    volumes:
      - ./container-fs/minion-etc-overlay:/opt/minion-etc-overlay
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.12
        ipv6_address: fd23:9695:aa65:fff0::12
      net.fulda:
        ipv4_address: 172.31.0.12
        ipv6_address: fd23:9695:aa65:fff1::12

  srv-stuttgart-01:
    image: quay.io/labmonkeys/net-snmp:5.9.4-r0.20240919.b3342
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64m
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.32
        ipv6_address: fd23:9695:aa65:fff0::32

  srv-stuttgart-02:
    image: quay.io/labmonkeys/net-snmp:5.9.4-r0.20240919.b3342
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64m
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.33
        ipv6_address: fd23:9695:aa65:fff0::33

  web-stuttgart-01:
    image: httpd
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64m
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.34
        ipv6_address: fd23:9695:aa65:fff0::34

  srv-fulda-01:
    image: quay.io/labmonkeys/net-snmp:5.9.4-r0.20240919.b3342
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64m
    networks:
      net.fulda:
        ipv4_address: 172.31.0.32
        ipv6_address: fd23:9695:aa65:fff1::32

  srv-fulda-02:
    image: quay.io/labmonkeys/net-snmp:5.9.4-r0.20240919.b3342
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64m
    networks:
      net.fulda:
        ipv4_address: 172.31.0.33
        ipv6_address: fd23:9695:aa65:fff1::33

  web-fulda-01:
    image: httpd
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64m
    networks:
      net.fulda:
        ipv4_address: 172.31.0.34
        ipv6_address: fd23:9695:aa65:fff1::34

networks:
  net.stuttgart:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/16
          - subnet: fd23:9695:aa65:fff0::/64
  net.fulda:
      driver: bridge
      ipam:
        config:
          - subnet: 172.31.0.0/16
          - subnet: fd23:9695:aa65:fff1::/64
