---
services:

  activemq:
    build:
      context: activemq
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512m
    environment:
      TZ: 'UTC'
    volumes:
      - 'data_activemq:/opt/activemq/data'
    ports:
      - '61616/tcp'

volumes:
  data_activemq: {}
