---
services:
  cortex:
    image: quay.io/cortexproject/cortex:v1.19.0
    command:
      - -config.file=/config/single-process-config.yaml
    volumes:
      - ./cortex/single-process-config.yaml:/config/single-process-config.yaml:ro
      - data-cortex:/data
    ports:
      - "9009/tcp"
    healthcheck:
      test: wget -qO- http://127.0.0.1:9009/ready
      interval: 2s
      timeout: 1s
      retries: 10

volumes:
  data-cortex: {}
