---
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.3
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 4g
    environment:
      TZ: UTC
      discovery.type: single-node
      node.name: es-node-01
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
    ports:
      - "9200/tcp"
      - "9300/tcp"
    volumes:
      - data_es:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins/:/usr/share/elasticsearch/plugins
    healthcheck:
      test: curl http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 3s
      timeout: 2s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.3
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2g
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      TZ: UTC
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601/tcp"
    healthcheck:
      test: curl http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 50

volumes:
  data_es: {}
