---
services:

  kafka:
    image: apache/kafka:3.9.0
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - data-kafka:/var/lib/kafka
    ports:
      - "9092/tcp"  # Client connections
      - "9093/tcp"  # Controller communication
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka", "9092"]
      interval: 3s
      timeout: 1s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 512m
    environment:
      TZ: UTC
      KAFKA_CLUSTERS_0_NAME: ipc-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080/tcp"

volumes:
  data-kafka: {}