---
services:
  minio:
    image: quay.io/minio/minio:latest
    command:
      - server
      - /data
    ports:
      - "9000/tcp"
      - "9001/tcp"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: changeme!
    volumes:
      - data-minio:/data

volumes:
  data-minio: {}
