---
services:

  onms-hzn-core:
    image: opennms/horizon:33.0.9
    depends_on:
      database:
        condition: service_healthy
    environment:
      TZ: UTC
    command: ["-s"]
    volumes:
      - data_onms_hzn_cfg:/opt/opennms/etc
      - data_onms_hzn:/opennms-data
    ports:
      - "8101/tcp"
      - "8980/tcp"
      - "1162/udp"
      - "10514/udp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  data_onms_hzn_cfg: {}
  data_onms_hzn: {}
