---
services:

  sentinel:
    image: opennms/sentinel:latest
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 4g
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      TZ: UTC
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAVA_MIN_MEM: 512M
      JAVA_MAX_MEM: 2048M
    command: ["-f"]
    ports:
      - "8301/tcp"
