---
services:

  core:
    image: opennms/horizon:latest
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 8g
    depends_on:
      database:
        condition: service_healthy
    environment:
      TZ: UTC
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    command: ["-s"]
    volumes:
      - data-onms-hzn-cfg:/opt/opennms/etc
      - data-onms-hzn:/opennms-data
    ports:
      - "8101/tcp"
      - "8980/tcp"
      - "1162/udp"
      - "10514/udp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  data-onms-hzn-cfg: {}
  data-onms-hzn: {}
