---
services:

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      TZ: UTC
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VRL7FhR@mGw@djhS2A4 # Change me and overwrite the scv.jce file described in the README
    volumes:
      - data-pg:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - "5432/tcp"

volumes:
  data-pg: {}
