---
services:

  activemq:
    volumes:
      - ./container-fs/activemq/activemq-config.xml:/opt/activemq/conf/activemq-config.xml
    ports:
      - "61616:61616/tcp"

  core:
    depends_on:
      activemq:
        condition: service_started
    volumes:
      - ./container-fs/core-etc-overlay:/opt/opennms-etc-overlay
    ports:
      - "8980:8980/tcp"
  
  minion:
    depends_on:
      activemq:
        condition: service_started
    volumes:
      - ./container-fs/minion-etc-overlay:/opt/minion-etc-overlay
    ports:
      - "162:1162/udp"
      - "514:1514/udp"