name: Validate Docker Compose files
on:
  workflow_dispatch:
  push:

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/base-builder:ubuntu.0.1.2.b2
    steps:
      - uses: actions/checkout@v4
      - name: Validate Docker Compose files
        run: |
          find . -iname "compose.yml" -exec docker compose -f {} config \;
